# version: '3.5'

# services:

# volumes:
#     applications-sync:
#         external:
#             name: "applications-docker-sync"
version: '3'

services:
    workspace:
        volumes:
            - applications-docker-sync:/var/www:nocopy
    php-fpm:
        volumes:
            - applications-docker-sync:/var/www:nocopy
    apache2:
        volumes:
            - applications-docker-sync:/var/www:nocopy
    mysql:
        volumes:
            - applications-docker-sync:/var/www:nocopy
    redis:
        volumes:
            - applications-docker-sync:/var/www:nocopy

volumes:
    applications-docker-sync:
        external: true